#############################PACKAGE###################
library(dplyr)
library(readr)
library(stringr)
library(tidytext)
library(textclean)
library(katadasaR)
library(tokenizers)
library(tm)
library(wordcloud2)
library(ggplot2)
library(SnowballC)
library(e1071)
library(caret)
library(readxl)

##############################BEGINNING#################################
data <- read.csv2(file = "D:\\Skripsi\\INI SKRIPSI\\DATA\\datajiwa+.csv", header = TRUE)
nodup<-data[!duplicated(data),]
komen.df<-nodup%>%as.character(data$Ulasan)
###################CLEANING############
#common for any platform
komen.df <-tolower(komen.df)
komen.df <- gsub("@\\w+", "", komen.df)
komen.df <- gsub("#\\w+", '', komen.df)
komen.df <- gsub("RT\\w+", "", komen.df)
komen.df <- gsub("http.*", "", komen.df)
komen.df <- gsub("RT", "", komen.df)
komen.df <- sub("(['])|[[:punct:]]", "\\1", komen.df)
komen.df <-gsub("[[:digit:]]", " ", komen.df)
komen.df <- sub("(['])|[[:punct:]]", "\\1", komen.df)
komen.df<-gsub("apk", "aplikasi", komen.df)
komen.df<-gsub("apl", "aplikasi", komen.df)
komen.df<-gsub("aplikasiikasi", "aplikasi", komen.df)
komen.df<-gsub("[-]"," ", komen.df)
komen.df<- komen.df%>%
  replace_html()%>%
  replace_url()
komen.df<-replace_html(replace_emoji(komen.df))
komen.df<-gsub("[.]"," ", komen.df)
komen.df<-gsub("[,]"," ", komen.df)
komen.df<-gsub("[?]"," ", komen.df)
komen.df<-gsub("[!]"," ", komen.df)
komen.df<-gsub("[/]", "", komen.df)
komen.df<-gsub("[%]", "", komen.df)
komen.df<-gsub("[@]", "", komen.df)
komen.df<-gsub("[(]", "", komen.df)
komen.df<-gsub("[)]", "", komen.df)
komen.df<-gsub("[\"]", "", komen.df)
komen.df<-gsub("^","", komen.df)
komen.df<-gsub("[+]", "", komen.df)
komen.df<-gsub("[:]", "", komen.df)
komen.df<-gsub("[&]", "", komen.df)
komen.df<-gsub("b>", "", komen.df)
komen.df<-gsub("br>", "", komen.df)
komen.df<-gsub("[*]", "", komen.df)
komen.df<-gsub("&quot", "", komen.df)
komen.df<-gsub("<a href=", "", komen.df)
komen.df<-gsub("&amp", "", komen.df)
komen.df<-gsub("grinning", "", komen.df)
komen.df<-gsub("it&", "", komen.df)
komen.df<-gsub("face", "", komen.df)
komen.df<-gsub("tears of joy", "", komen.df)
komen.df<-gsub("big eyes", "", komen.df)
komen.df<-gsub("with", "", komen.df)
komen.df<-gsub("sweat", "", komen.df)
komen.df<-gsub("crying", "", komen.df)
komen.df<-gsub("thumbs up", "", komen.df)
komen.df<-gsub("flexed biceps", "", komen.df)
komen.df<-gsub("smiling eyes", "", komen.df)
komen.df<-gsub("sunglasses oncoming fist", "", komen.df)
komen.df<-gsub("expressionless face moai", "", komen.df)
komen.df<-gsub("full moon face", "", komen.df)
komen.df<-gsub("beaming","", komen.df)
komen.df<-gsub("red heart", "", komen.df)
komen.df<-gsub("loudly", "", komen.df)
komen.df<-gsub("smiling", "", komen.df)
komen.df<-gsub("globe showing Americas heavy heart exclamation", "", komen.df)
komen.df<-gsub("dashing away", "", komen.df)
komen.df<-gsub("open mouth", "", komen.df)
komen.df<-gsub("heart-eyes", "", komen.df)
komen.df<-gsub("horns", "", komen.df)
komen.df<-gsub("bomb", "", komen.df)
komen.df<-gsub("angry", "", komen.df)
komen.df<-gsub("steam from nose pouting", "", komen.df)
komen.df<-gsub("pouting", "", komen.df)
komen.df<-gsub("folded", "", komen.df)
komen.df<-gsub("hands", "", komen.df)
komen.df<-gsub("steam from nose", "", komen.df)
komen.df<-gsub("OK hand", "", komen.df)
komen.df<-gsub("thumbs down", "", komen.df)
komen.df<-gsub("raising", "", komen.df)
komen.df<-gsub("weary", "", komen.df)
komen.df<-gsub("relieved", "", komen.df)
komen.df<-gsub("cross mark", "", komen.df)
komen.df<-gsub("smirking", "", komen.df)
komen.df<-gsub("heart suit", "", komen.df)
komen.df<-gsub("new moon", "", komen.df)
komen.df<-gsub("unamused", "", komen.df)

komen.df<-gsub("lg pingin", "lagi ingin", komen.df)
komen.df<-gsub("trs pesen", "terus pesan", komen.df)
komen.df<-gsub("gedee", "besar", komen.df)
komen.df<-gsub("cakepp hrs", "cakep harus", komen.df)
komen.df<-gsub("seger", "segar", komen.df)
komen.df<-gsub("ga bikin", "tidak bikin", komen.df)
komen.df<-gsub("puyeng", "pusing", komen.df)
komen.df<-gsub("jugak", "juga", komen.df)
komen.df<-gsub("no worries lg", "tidak perlu khawatir lagi", komen.df)
komen.df<-gsub("ga perlu", "tidak perlu", komen.df)
komen.df<-gsub("ga cuma", "tidak cuma", komen.df)
komen.df<-gsub("simple ga ribet", 'sederhana tidak ribet', komen.df)
komen.df<-gsub("lemot", "lambat", komen.df)
komen.df<-gsub("gokil", "keren", komen.df)
komen.df<-gsub("gausah", "tidak perlu", komen.df)
komen.df<-gsub("ga bisa", "tidak bisa", komen.df)
komen.df<-gsub("auto happy kl", "langsung senang kalau", komen.df)
komen.df<-gsub("trs pas lg", "trus pas lagi", komen.df)
komen.df<-gsub("parkpelayan", "park pelayan", komen.df)
komen.df<-gsub("even gw", "walaupun aku", komen.df)
komen.df<-gsub("enaknya", "enak nya", komen.df)
komen.df<-gsub("simplee", "sederhana", komen.df)
komen.df<-gsub("gak perlu", "tidak perlu", komen.df)
komen.df<-gsub("mayan bgt", "lumayan banget", komen.df)
komen.df<-gsub("ptongan", "potongan", komen.df)
komen.df<-gsub("lelet", "lambat", komen.df)
komen.df<-gsub("betullaa", 'banget', komen.df)
komen.df<-gsub("kmrn", "kemaren", komen.df)
komen.df<-gsub("promoo", "promo", komen.df)
komen.df<-gsub("gak nunggu", "tidak perlu menunggu", komen.df)
komen.df<-gsub("great app", "aplikasi bagus", komen.df)
komen.df<-gsub("i could say jiwa ini easy to use terutama buat yg beginner user gaakan pusing karna appnya clean dan simple", 
               "aku bisa bilang jiwa ini mudah digunakan terutama buat pengguna baru dan tidak akan pusing karena aplikasinya bersih dan sederhana", komen.df)
komen.df<-gsub("good", "bagus", komen.df)
komen.df<-gsub("parahhhhh", "parah", komen.df)
komen.df<-gsub("gamau antrii", "tidak mau antri", komen.df)
komen.df<-gsub("they make it simple", "mereka bikin tampilannya sederhana", komen.df)
komen.df<-gsub("trima smua", "terima semua", komen.df)
komen.df<-gsub("no more", "tidak perlu", komen.df)
komen.df<-gsub("lamgsung", "langsung", komen.df)
komen.df<-gsub("refund", "pengembalian dana", komen.df)
komen.df<-gsub("gilak", "gila", komen.df)
komen.df<-gsub("bgt", "banget", komen.df)
komen.df<-gsub("gausa", "tidak usah", komen.df)
komen.df<-gsub("ndak", "tidak", komen.df)
komen.df<-gsub("mantep pol", "mantap banget", komen.df)
komen.df<-gsub("nytpi kok gk", "nya tapi kenapa tidak", komen.df)
komen.df<-gsub("exellent maknyuzzz", "mantap enak", komen.df)
komen.df<-gsub("simple clean gampang dipake", "sederhana bersih mudah dipakai", komen.df)
komen.df<-gsub("makasih banyak", "terima kasih banyak", komen.df)
komen.df<-gsub("trobel", "bermasalah", komen.df)
komen.df<-gsub("boncos", "boros", komen.df)
komen.df<-gsub("php promo", "penipu promo", komen.df)
komen.df<-gsub("tp gak bisa dipesen", "tapi tidak bisa dipesan", komen.df)
komen.df<-gsub("ilfil", "tidak suka", komen.df)
komen.df<-gsub("brisik", "berisik", komen.df)
komen.df<-gsub("gosah", 'ga usah', komen.df)
komen.df<-gsub("gbisa gjls", "tidak bisa tidak jelas",komen.df)
komen.df<-gsub("gk ada", "tidak ada", komen.df)
komen.df<-gsub("bngt harus", "banget harus", komen.df)
komen.df<-gsub("gk ush", "tidak usah", komen.df)
komen.df<-gsub("ngelag", "lambat", komen.df)
komen.df<-gsub("krn ada", "karena ada", komen.df)
komen.df<-gsub("enakeun", 'enak', komen.df)
komen.df<-gsub("ilanggggggggg", "hilang", komen.df)
komen.df<-gsub("gk pernah", "tidak pernah", komen.df)
komen.df<-gsub("dcancel", "di cancel", komen.df)
komen.df<-gsub("murahhh", "murah", komen.df)
komen.df<-gsub("beneficial", "menguntungkan", komen.df)
komen.df<-gsub("useful", "berguna", komen.df)
komen.df<-gsub("recomended", "berguna", komen.df)
komen.df<-gsub("tdk bsa dibukak", "tidak bisa dibuka", komen.df)
komen.df<-gsub("ngk usah", "tidak usah", komen.df)
komen.df<-gsub("gg enak", "tidak enak", komen.df)
komen.df<-gsub("gg di cek", "tidak dicek", komen.df)
komen.df<-gsub("ga kaya yg dulu cepat n mudah", "tidak seperti dulu cepat dan mudah", komen.df)
komen.df<-gsub("kalo gak niat buat promo", "kalau tidak niat bikin promo", komen.df)
komen.df<-gsub("ngebantu ngehemat", "membantu menghemat", komen.df)
komen.df<-gsub("boongan", "bohong", komen.df)
komen.df<-gsub("abisss", "habis", komen.df)
komen.df<-gsub("gk nian gk usah", "tidak niat tidak usah", komen.df)
komen.df<-gsub("no drama", "lancar", komen.df)
komen.df<-gsub("abisabis", "habis", komen.df)
komen.df<-gsub("cpt pesanankdng", "cepat kadang pesanan", komen.df)
komen.df<-gsub("cakeepp", "bagus", komen.df)
komen.df<-gsub("mesennya harus ber kali kali bru bisa di approve kadang kepesen kadang dibatalain banyak dibatalinnya", 
               "pemesanan harus berulang kali baru bisa diterima kadang kepesen kadang dibatalin banyak dibatalinnya ", komen.df)
komen.df<-gsub("n'kental", "dan kental", komen.df)
komen.df<-gsub("ko bisa gitu", "kenapa bisa begitu", komen.df)
komen.df<-gsub("knpa tidak bisa", "kenapa tidak bisa", komen.df)
komen.df<-gsub("tdk ada outlet", "tidak ada outlet", komen.df)
komen.df<-gsub("vouch untuk pengguna", "voucher untuk pengguna", komen.df)
komen.df<-gsub("tdk butuh", "tidak butuh", komen.df)
komen.df<-gsub("gaada", "tidak ada", komen.df)
komen.df<-gsub("fine fine ajh   disini doang nih   paraaaaaaahhh", "aman aja disini doang nih parah", komen.df)
komen.df<-gsub("waraas", "waras", komen.df)
komen.df<-gsub("jd g bisa", "jadi tidak bisa", komen.df)
komen.df<-gsub("udar coba gerai bayar pake ovo  bayar pake gopay  semuax diredund   entah alasanx apa", 
               "udah coba gerai bayar pake ovo  bayar pake gopay  semuanya direfund   entah alasannya apa", komen.df)
komen.df<-gsub("siiiip", "mantap", komen.df)
komen.df<-gsub("membagongkan", "menjengkelkan", komen.df)
komen.df<-gsub("mantaap", "mantap", komen.df)
komen.df<-gsub("friendly useeeer", "memudahkan pengguna", komen.df)
komen.df<-gsub("teruscape", "terus cape", komen.df)
komen.df<-gsub("senengg", "senang", komen.df)
komen.df<-gsub("tdk bisa digunakan gatau deh salahnya dmn", "tidak bisa digunakan tidak tau deh salahnya dimana", komen.df)
komen.df<-gsub("trimakasih  sekarang dah lebih baik  keep ur bagus work janjiw and crew", 
               "terima kasih  sekarang sudah lebih baik  kerja bagus janjiw and crew", komen.df)
komen.df<-gsub("tnpa pembritahuan atau penjelasan jika tkut rugi jngan",
               "tanpa pemberitahuan atau penjelasan jika takut rugi jangan", komen.df)
komen.df<-gsub("okeee", "oke", komen.df)
komen.df<-gsub("logind", "login", komen.df)
komen.df<-gsub("sukaaaa banget sama aplikasi jiwa skrgg yg", "suka banget sama aplikasi jiwa sekarang yang", komen.df)
komen.df<-gsub("gw download ini cmn karna cwe gw", "aku download ini hanya karena pacarku", komen.df)
komen.df<-gsub("happyy", "senang", komen.df)
komen.df<-gsub("lewak", "lewat", komen.df)
komen.df<-gsub("koints", "poin", komen.df)
komen.df<-gsub("bnr bnr tampilan appnya cakep banget simple mempermudah kita mau pencet apa  trs tinggal pickup dan ambil jd gk perlu ngantre", 
               "beneran tampilan aplikasinya bagus banget sederhana mempermudah kita mau pencet apa  terus tinggal pickup dan ambil jadi tidak perlu ngantre", komen.df)
komen.df<-gsub("gkk ribet","tidak ribet", komen.df)
komen.df<-gsub("worth it", "untung", komen.df)
komen.df<-gsub("mat matttt", "", komen.df)
komen.df<-gsub("gaperlu", "tidak perlu", komen.df)
komen.df<-gsub("cuan", "untung", komen.df)
komen.df<-gsub("worthit", "untung", komen.df)
komen.df<-gsub("bnyk", "banyak", komen.df)
komen.df<-gsub("murce", "murah", komen.df)
komen.df<-gsub("disii jg", "disini juga", komen.df)
komen.df<-gsub("bs dptin vocer lagiii", "bisa dapat voucher lagi", komen.df)
komen.df<-gsub("lg takut kere", "lagi takut miskin", komen.df)
komen.df<-gsub("voucher dics", "voucher diskon", komen.df)
komen.df<-gsub("enjoy", "senang", komen.df)
komen.df<-gsub("jutidak", "juga", komen.df)
komen.df<-gsub("gabsa", "tidak bisa", komen.df)
komen.df<-gsub("smoga kedepannya", "semoga kedepannya", komen.df)
komen.df<-gsub("kaga guna", "tidak berguna", komen.df)
komen.df<-gsub("tdk bisa diorder", "tidak bisa diorder", komen.df)
komen.df<-gsub("tampiilan aplikasinya simpel katidak", "tampilan aplikasinya sederhana tidak", komen.df)
komen.df<-gsub("cepet banget siiii cepet banget","cepat banget si cepat banget", komen.df)
komen.df<-gsub("better banget", "lebih baik banget", komen.df)
komen.df<-gsub("gada pdhal biasa beli d sana", "tidak ada padhal biasa beli di sana", komen.df)
komen.df<-gsub("aposehh ganiat ngei promo yo", "apasih tidak niat memberi promo ya", komen.df)
komen.df<-gsub("kok gaisok terus asuu", "kenapa tidak bisa terus", komen.df)
komen.df<-gsub("trouble", "bermasalah", komen.df)
komen.df<-gsub("kacauu", "kacau", komen.df)
komen.df<-gsub("ngang ngong ngang ngong", "lama", komen.df)
komen.df<-gsub("berar dan", "berat dan", komen.df)
komen.df<-gsub("gimmick", "penipuan", komen.df)
komen.df<-gsub("harua loginmau", "harus login mau", komen.df)
komen.df<-gsub("voucher disc", "voucher diskon", komen.df)
komen.df<-gsub("baguss dan banyak", "bagus dan banyak", komen.df)
komen.df<-gsub("so good", "sangat bagus", komen.df)
komen.df<-gsub("first of all ui designnya perlu diapresiasi soalnya clean tp tetep informative  ditambah lg krn udah sejalan sm rebrand mereka yg baru  jadinya jauh lebih segar aja liatnyaaa", 
               "pertama tama tampilan designnya perlu diapresiasi soalnya sederhana tapi tetap informatif ditambah lagi karena udah sejalan sama rebrand mereka yg baru  jadinya jauh lebih segar aja liatnya", komen.df)
komen.df<-gsub("flash sale", "diskon", komen.df)
komen.df<-gsub("mantepp bangett", "mantap banget", komen.df)
komen.df<-gsub("d ambil blm d bikin mulubukan", "di ambil belum di bikin mulu bukan", komen.df)
komen.df<-gsub("flas sale outlet", "diskon outlet", komen.df)
komen.df<-gsub("gaakan ketinggalan", "tidak akan ketinggalan", komen.df)
komen.df<-gsub("info disc dan new arrival", "info diskon dan menu baru", komen.df)
komen.df<-gsub("terdekatt", "terdekat", komen.df)
komen.df<-gsub("pemabatalanedit", 'pembatalan edit', komen.df)
komen.df<-gsub("sangatta", "sangat", komen.df)
komen.df<-gsub("terimaproses", "terima proses", komen.df)
komen.df<-gsub("gkk perlu ngantre lg asik banget dahh jd satset", "tidak perlu ngantri lagi asik banget dah jadi cepat", komen.df)
komen.df<-gsub("first impression", "kesan pertama", komen.df)
komen.df<-gsub("smangat developer", "semagat developer", komen.df)
komen.df<-gsub("memfix bug", "memperbaiki eror", komen.df)
komen.df<-gsub("gk dibenahin", "tidak dibenahin", komen.df)
komen.df<-gsub("flashsale", "diskon", komen.df)
komen.df<-gsub("berdayaguna", "berdaya guna", komen.df)
komen.df<-gsub("yasmpe x", "ya sampe", komen.df)
komen.df<-gsub("persevering tolong di follow up", "per penyajian tolong di cek", komen.df)
komen.df<-gsub("crash", "eror", komen.df)
komen.df<-gsub("very bagus", "sangat bagus", komen.df)
komen.df<-gsub("bagusss bangetttt", "bagus banget", komen.df)
komen.df<-gsub("canceled", "dibatalkan", komen.df)
komen.df<-gsub("voucer", "voucher", komen.df)
komen.df<-gsub("blm pesan", "belum pesan", komen.df)
komen.df<-gsub("event flashsale", "diskon", komen.df)
komen.df<-gsub("ga jls aplikasinya", "tidak jelas aplikasinya", komen.df)
komen.df<-gsub("overall", "sejauh ini", komen.df)
komen.df<-gsub("menuhmenuhin", "bikin penuh", komen.df)
komen.df<-gsub("se ring banget kudu di upgrade mana mau upgrade gk bisa jd", 
               "sering banget harus diperbarui mana mau perbarui tidak bisa jadi", komen.df)
komen.df<-gsub("males", "malas", komen.df)
komen.df<-gsub("pesen", "pesan", komen.df)
komen.df<-gsub("bingits", "banget", komen.df)
komen.df<-gsub("sesuaimalah", "sesuai malah", komen.df)
komen.df<-gsub("sebelahuntuk", "sebelah untuk", komen.df)
komen.df<-gsub("sichjujur", "sih jujur", komen.df)
komen.df<-gsub("gk jelas statusnya", "tidak jelas statusnya", komen.df)
komen.df<-gsub("bru update kok suruh update teros", 'baru update kenapa suruh update terus', komen.df)
komen.df<-gsub("inimau", "ini mau", komen.df)
komen.df<-gsub("kacauu", "kacau", komen.df)
komen.df<-gsub("jatidak", "jaga", komen.df)
komen.df<-gsub("ngtidak", "tidak", komen.df)
komen.df<-gsub("kaga jelas", "tidak jelas", komen.df)
komen.df<-gsub("g niat buat aplikasi", 'tidak niat buat aplikasi', komen.df)
komen.df<-gsub("se olah", "seolah", komen.df)
komen.df<-gsub("kembalilan", "kembalikan", komen.df)
komen.df<-gsub("inii", "ini", komen.df)
komen.df<-gsub("ga guna", "tidak berguna", komen.df)
komen.df<-gsub("daftarlogin", "daftar login", komen.df)
komen.df<-gsub("sayasebagai", "saya sebagai", komen.df)
komen.df<-gsub("orderanlama", "orderan lama", komen.df)
komen.df<-gsub("gmna sih vchr tidak bisa dipake ngpn", "gimana sih voucher tidak bisa dipakai kenapa", komen.df)
komen.df<-gsub("notif sgala klw ga bs di", "notifikasi segala kalau tidak bisa di", komen.df)
komen.df<-gsub("jg sama taiiii klw ga bs pake jgn php in org mw pesen lwt", 
               "juga sama tai kalau tidak bisa dipakai jangan beri harapan ke orang mau pesan lewat", komen.df)
komen.df<-gsub("dlu sana aplikasi baru gua pesen bikin ksl", "dulu sana aplikasi baru aku pesan bikin kesal", komen.df)
komen.df<-gsub("kesanadriver", "kesana driver", komen.df)
komen.df<-gsub("tdk dapat digunakan", "tidak dapat digunakan", komen.df)
komen.df<-gsub("app bapuk", "aplikasi jelek", komen.df)
komen.df<-gsub("tp gak dpt diskonnya", "tapi tidak dapat diskon", komen.df)
komen.df<-gsub("gak guna", "tidak berguna", komen.df)
komen.df<-gsub("pickupdeliveru", "ambil sendiri", komen.df)
komen.df<-gsub("linkternyata", "link ternyata", komen.df)
komen.df<-gsub("aplikasicumak", "aplikasi cuma", komen.df)
komen.df<-gsub("gbs di tukarkan", "tidak bisa ditukarkan", komen.df)
komen.df<-gsub("kog tidak bisa", "kenapa tidak bisa", komen.df)
komen.df<-gsub("timurbad app", "timur jelek aplikasi", komen.df)
komen.df<-gsub("permantap", "mantap", komen.df)
komen.df<-gsub("happy bnyk disc nyamoga srg ada disc ya", "senang banyak diskon nya semoga sering ada diskon ya", komen.df)
komen.df<-gsub("gk jls lambat", "tidak jelas lambat", komen.df)
komen.df<-gsub("gk bsa pesen", "tidak bisa pesan", komen.df)
komen.df<-gsub("aplikasi nya bner", "aplikasi nya benar", komen.df)
komen.df<-gsub("susah bgd mau pesennya even gak bisa", "susah banget mau pesannya malah bahkan tidak bisa", komen.df)
komen.df<-gsub("kureng", "kurang", komen.df)
komen.df<-gsub("mleset jauh bangetgak", "meleset jauh banget tidak", komen.df)
komen.df<-gsub("gabisa masukin vocherrrr", "tidak bisa memasukkan voucher", komen.df)
komen.df<-gsub("seperfect", "sebaik", komen.df)
komen.df<-gsub("bye aja", "tinggalkan saja", komen.df)
komen.df<-gsub("gk responsif", "tidak responsif", komen.df)
komen.df<-gsub("kagak ada katanya si mbak","tidak ada katanya si mbak", komen.df)
komen.df<-gsub("expaired", "kadaluarsa", komen.df)
komen.df<-gsub("outletnyabgabisa", "outletnya tidak bisa", komen.df)
komen.df<-gsub("pekok aplikasi gak guno", "bodoh aplikasi tidak berguna", komen.df)
komen.df<-gsub("mantapp", "mantap", komen.df)
komen.df<-gsub("loding trus dan gak bnyak", "proses terus dan tidak banyak", komen.df)
komen.df<-gsub("sat set sat set", "cepat", komen.df)
komen.df<-gsub("ga beres", "tidak beres", komen.df)
komen.df<-gsub("di cancelled", "dibatalkan", komen.df)
komen.df<-gsub("disc tipu", "diskon menipu", komen.df)
komen.df<-gsub("detect", "kedata", komen.df)
komen.df<-gsub("ribetttt", "ribet", komen.df)
komen.df<-gsub("gua gk bisa", "aku tidak bisa", komen.df)
komen.df<-gsub("melenceng sebdiri", "melenceng sendiri", komen.df)
komen.df<-gsub("lulumayan", "lumayan", komen.df)
komen.df<-gsub("bagusdeals", "gooddeals", komen.df)
komen.df<-gsub("bagus deals", "good deals", komen.df)
komen.df<-gsub("ga bkin", "ga bikin", komen.df)

komen.df<-stripWhitespace(komen.df)

#menghapus data yang tidak berisi ulasan
komen.df<-komen.df[-c(11,24,71,81,110,113,119,136,142,145,150,175,
                      184,193,208,231,236,240,246,248,250,259,271,302,306,
                      312,339,345,358,364,401,444,432,451,460,481,496,
                      502,525,533,544,547)]


komen.df<-komen.df[-c(164,205,251,500,547)]

#############WORDCLOUD & BARCHART##################
docs<-Corpus(VectorSource(komen.df))
stop<-readLines("~/id.stopwords.02.01.2016.txt")
docs<-tm_map(docs,removeWords,c('aplikasi',"jiwa", 'app','aplikasinya','banget','gak','aja','udah','nya',
                                "pake",'pas','kali','sih','bikin','kalo','mulu','dapet','gitu','klo','udh','dah',
                                'cek','trs','emang','gini','oke','deh'))
docs<-tm_map(docs,removeWords,stop)

{
  dtm<-TermDocumentMatrix(docs)
  m<-as.matrix(dtm)
  v<-sort(rowSums(m),decreasing = TRUE)
  d<-data.frame(word=names(v),freq=v)
}

wordcloud2(d, backgroundColor = "white",
           color = "random-light", size = 0.4)

d%>%
  filter(freq>=30)%>%
  mutate(word=reorder(word,freq))%>%
  ggplot(aes(word,freq,fill=word))+
  geom_bar(stat='identity')+
  xlab('Kata')+
  ylab('Frekuensi')+
  ggtitle(paste("Kata-Kata yang Paling Sering Muncul Pada Komentar"))+
  theme(legend.position = "none")+
  coord_flip()

###############LEXICON BASED###################################

dataframe<-data.frame(text=unlist(sapply(docs,'[')), stringsAsFactors = F)

kalimat2<-dataframe

pos<-readLines("~/s-neg.txt")
neg<-readLines("~/s-pos.txt")

kata.positif=c(pos)
kata.negatif=c(neg)


scores.sentiment<-function(kalimat2, kata.positif, kata.negatif, .progress = 'none')
{
  require(plyr)
  require(stringr)
  scores = laply(kalimat2, function(kalimat, kata.positif, kata.negatif) {
    list.kata = str_split(kalimat, '\\s+')
    kata2 = unlist(list.kata)
    positif.matches = match(kata2, kata.positif)
    negatif.matches = match(kata2, kata.negatif)
    positif.matches = !is.na(positif.matches)
    negatif.matches = !is.na(negatif.matches)
    score = sum(positif.matches)-(sum(negatif.matches))
    return(score)
  }, kata.positif, kata.negatif, .progress = .progress)
  scores.df = data.frame(score = scores, text = kalimat2)
  return(scores.df)
}

hasil <- scores.sentiment(komen.df, kata.positif, kata.negatif, .progress = 'text')


hasil$klasifikasi<-ifelse(hasil$score < 0, "Negatif", ifelse(hasil$score > 0, "Positif", "Netral"))
kategori_sentimen_2<-cbind(hasil$klasifikasi)
table(kategori_sentimen_2)


gabung<-data.frame(komen.df, hasil, stringsAsFactors = F)

data.pos<-gabung[gabung$score>0,]

data.neg<-gabung[gabung$score<0,]


data.net<-gabung[gabung$score==0,]


positif<-subset(gabung, klasifikasi == "Positif")
negatif<-subset(gabung, klasifikasi == "Negatif")
netral<-subset(gabung, klasifikasi == "Netral")
gabung$text<-stripWhitespace(gabung$text)
